import { Listing } from "./listings.types";

export const mockListings: Listing[] = [
  {
    listingId: "L001",
    address: {
      street: "123 Oak Street",
      city: "Portland",
      state: "OR",
      zip: "97201",
    },
    price: 825000,
    bedrooms: 3,
    bathrooms: 2,
    status: "Active",
  },
  {
    listingId: "L002",
    address: {
      street: "456 Pine Avenue",
      city: "Portland",
      state: "OR",
      zip: "97205",
    },
    price: 799000,
    bedrooms: 4,
    bathrooms: 3,
    status: "Active",
  },
  {
    listingId: "L003",
    address: {
      street: "789 Maple Drive",
      city: "Seattle",
      state: "WA",
      zip: "98101",
    },
    price: 1250000,
    bedrooms: 5,
    bathrooms: 3.5,
    status: "Active",
  },
  {
    listingId: "L004",
    address: {
      street: "321 Cedar Lane",
      city: "Portland",
      state: "OR",
      zip: "97202",
    },
    price: 650000,
    bedrooms: 2,
    bathrooms: 2,
    status: "Pending",
  },
  {
    listingId: "L005",
    address: {
      street: "654 Birch Way",
      city: "Seattle",
      state: "WA",
      zip: "98102",
    },
    price: 950000,
    bedrooms: 3,
    bathrooms: 2.5,
    status: "Active",
  },
  {
    listingId: "L006",
    address: {
      street: "987 Elm Court",
      city: "Portland",
      state: "OR",
      zip: "97210",
    },
    price: 1100000,
    bedrooms: 4,
    bathrooms: 3,
    status: "Sold",
  },
  {
    listingId: "L007",
    address: {
      street: "147 Spruce Street",
      city: "Bellevue",
      state: "WA",
      zip: "98004",
    },
    price: 1850000,
    bedrooms: 5,
    bathrooms: 4,
    status: "Active",
  },
  {
    listingId: "L008",
    address: {
      street: "258 Willow Place",
      city: "Portland",
      state: "OR",
      zip: "97211",
    },
    price: 575000,
    bedrooms: 3,
    bathrooms: 1.5,
    status: "Active",
  },
  {
    listingId: "L009",
    address: {
      street: "369 Ash Boulevard",
      city: "Seattle",
      state: "WA",
      zip: "98103",
    },
    price: 720000,
    bedrooms: 2,
    bathrooms: 1,
    status: "Active",
  },
  {
    listingId: "L010",
    address: {
      street: "741 Poplar Road",
      city: "Portland",
      state: "OR",
      zip: "97212",
    },
    price: 890000,
    bedrooms: 4,
    bathrooms: 2.5,
    status: "Pending",
  },
  {
    listingId: "L011",
    address: {
      street: "852 Sycamore Avenue",
      city: "Bellevue",
      state: "WA",
      zip: "98005",
    },
    price: 2200000,
    bedrooms: 6,
    bathrooms: 5,
    status: "Active",
  },
  {
    listingId: "L012",
    address: {
      street: "963 Juniper Drive",
      city: "Portland",
      state: "OR",
      zip: "97213",
    },
    price: 425000,
    bedrooms: 2,
    bathrooms: 1,
    status: "Active",
  },
  {
    listingId: "L013",
    address: {
      street: "159 Magnolia Street",
      city: "Seattle",
      state: "WA",
      zip: "98104",
    },
    price: 1150000,
    bedrooms: 3,
    bathrooms: 3,
    status: "Sold",
  },
  {
    listingId: "L014",
    address: {
      street: "753 Redwood Lane",
      city: "Portland",
      state: "OR",
      zip: "97214",
    },
    price: 675000,
    bedrooms: 3,
    bathrooms: 2,
    status: "Active",
  },
  {
    listingId: "L015",
    address: {
      street: "486 Hickory Court",
      city: "Kirkland",
      state: "WA",
      zip: "98033",
    },
    price: 1350000,
    bedrooms: 4,
    bathrooms: 3.5,
    status: "Active",
  },
  {
    listingId: "L016",
    address: {
      street: "627 Cherry Street",
      city: "Portland",
      state: "OR",
      zip: "97215",
    },
    price: 520000,
    bedrooms: 2,
    bathrooms: 1.5,
    status: "Active",
  },
  {
    listingId: "L017",
    address: {
      street: "834 Walnut Avenue",
      city: "Seattle",
      state: "WA",
      zip: "98105",
    },
    price: 985000,
    bedrooms: 4,
    bathrooms: 2,
    status: "Pending",
  },
  {
    listingId: "L018",
    address: {
      street: "951 Chestnut Drive",
      city: "Portland",
      state: "OR",
      zip: "97216",
    },
    price: 715000,
    bedrooms: 3,
    bathrooms: 2.5,
    status: "Active",
  },
  {
    listingId: "L019",
    address: {
      street: "246 Beech Road",
      city: "Redmond",
      state: "WA",
      zip: "98052",
    },
    price: 1425000,
    bedrooms: 5,
    bathrooms: 3,
    status: "Active",
  },
  {
    listingId: "L020",
    address: {
      street: "573 Alder Street",
      city: "Portland",
      state: "OR",
      zip: "97217",
    },
    price: 595000,
    bedrooms: 3,
    bathrooms: 2,
    status: "Sold",
  },
];
